### ISSUE TITLE
A mis-matched display address & positioning address on 徐汇区老沪闵路

### ISSUE THREAD

**Issue by aoholic** [TienZhao/covid-shanghai#2] opened 2022-03-15 07:12 UTC
Hi Tien, 

Thanks for your wonderful work, that's really helpful for us to learn about what's actually happening around our neighborhood!!!

Just want to leave a kind note a fact-check here:

My friend lives in 徐汇区老沪闵路439弄小区 and she's locked down there. 
The mask emoji appears correctly on her spot but the displayed address is 296: 徐汇区老沪闵路1039弄, which is far far away from there. 

Just want to shout out this info to eliminate confusion. 

Again big thanks for your contribution!! 

![image](https://user-images.githubusercontent.com/88048564/158325087-4691a48b-7b57-4037-81a5-ff8fbcafb581.png)

**Comment by TienZhao** [comment] 2022-03-15 07:34
Address 296: 徐汇区老沪闵路1039弄 is intended for its literal meaning, which is parsed from the announcement on 11 March, "无症状感染者44，女，55岁，居住于徐汇区老沪闵路1039弄" 
Link: https://wsjkw.sh.gov.cn/xwfb/20220312/559cc1eb3e9646b6a08b28ce340a3463.html

It is misplaced because Baidu map API responds with a wrong default geolocation. I'll try to fix it with more accurate address strings in the future commits, as done in https://github.com/TienZhao/covid-shanghai/blob/main/main.py#L10
If you are familiar with python, you can create a pull request, too.

Also, it is necessary to mention that the map only plots the addresses with confirmed cases, while the lockdown area could be much larger than that.

Finally, many thanks to your bug report. I'm glad that this project is helpful to you and your friends! 😊

**Comment by TienZhao** [comment] 2022-03-15 07:41
Fixed in [commit f204edd](https://github.com/TienZhao/covid-shanghai/commit/f204eddf4d7158a3157413c00a81bbce2ee0c306) along with the update of March 15 data.

**Closed as completed by TienZhao** 2022-03-15 07:41 UTC
